name: import-system-symbols-from-ipsw

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: "Set up GCP access"
      uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935
      with:
        workload_identity_provider: projects/868781662168/locations/global/workloadIdentityPools/prod-github/providers/github-oidc-pool
        service_account: gha-apple-system-symbols@sac-prod-sa.iam.gserviceaccount.com
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
    - name: "Install dependencies"
      shell: bash
      run: brew install lzip keith/formulae/dyld-shared-cache-extractor
    - name: "Compile ios-utils"
      shell: bash
      run: cd ios-utils && make
    - name: "Install symsorter"
      shell: bash
      run: |
        set -eou pipefail
        curl -L https://github.com/getsentry/symbolicator/releases/download/0.4.2/symsorter-Darwin-universal > symsorter
        chmod +x symsorter
    - name: "Install Python dependencies"
      shell: bash
      run: python3 -m pip install --user -r requirements.txt
    - name: Install sentry-cli
      shell: bash
      # Pin cli version so builds are reproducible
      run: curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION=2.21.2 sh
    - name: Install ipsw
      shell: bash
      run: brew install ipsw
