name: import-system-symbols-from-ipsw
inputs:
  gcp_service_key:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: "Install Google Cloud SDK"
      shell: bash
      run: |
        brew install --cask google-cloud-sdk
        echo "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" >> $GITHUB_PATH
    - name: "Set up GCP access"
      shell: bash
      env:
        GCP_SERVICE_KEY: ${{ inputs.gcp_service_key }}
      run: |
        set -eou pipefail
        mkdir -p ~/.gcp
        key_path="$HOME/.gcp/key.json"
        echo $GCP_SERVICE_KEY > "$key_path"
        gcloud auth activate-service-account --key-file="$key_path"
    - name: "Install dependencies"
      shell: bash
      run: brew install p7zip lzip keith/formulae/dyld-shared-cache-extractor
    - name: "Compile ios-utils"
      shell: bash
      run: cd ios-utils && make
    - name: "Install symsorter"
      shell: bash
      run: |
        set -eou pipefail
        curl -L https://github.com/getsentry/symbolicator/releases/download/0.4.2/symsorter-Darwin-universal > symsorter
        chmod +x symsorter
    - name: "Install Python dependencies"
      shell: bash
      run: python3 -m pip install --user -r requirements.txt
    - name: Select Xcode version
      shell: bash
      run: sudo xcode-select -s /Applications/Xcode_13.3.app/Contents/Developer
    - name: Install sentry-cli
      shell: bash
      run: curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION=2.15.2 sh
