name: import-system-symbols-from-simulators
inputs:
  sentry_dsn:
    required: true
  sentry_auth_token:
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-import-system-symbols
    - name: Import symbols
      env:
          SENTRY_DSN: ${{ inputs.sentry_dsn }}
      shell: bash
      run: sentry-cli monitors run 430ded42-54cb-427b-8fc7-433ac9ca8da5 -- python3 import_system_symbols_from_simulators.py
