name: import-system-symbols-from-simulators
inputs:
  gcp_service_key:
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-import-system-symbols
      with:
        gcp_service_key: ${{ inputs.gcp_service_key }}
    - name: Import symbols
      shell: bash
      run: python3 import_system_symbols_from_simulators.py
