name: import-system-symbols-from-simulators
inputs:
  gcp_service_key:
    required: true
  sentry_auth_token:
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-import-system-symbols
      with:
        gcp_service_key: ${{ inputs.gcp_service_key }}
    - name: Import symbols
      shell: bash
      run: sentry-cli --auth-token ${{ inputs.sentry_auth_token }} monitors run 430ded42-54cb-427b-8fc7-433ac9ca8da5 -- python3 import_system_symbols_from_simulators.py
