name: import-system-symbols-from-ipsw
inputs:
  sentry_auth_token:
    required: true
  os_name:
    required: true
  os_version:
    default: 'latest'
  fetch_ipsw:
    default: true
  fetch_ota:
    default: false
  sentry_dsn:
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-import-system-symbols
    - name: Import symbols from IPSW
      env:
          SENTRY_DSN: ${{ inputs.sentry_dsn }}
      shell: bash
      if: ${{ inputs.fetch_ipsw }}
      run: sentry-cli monitors run ${{ inputs.cron_monitor_slug }} -- python3 import_system_symbols_from_ipsw.py --os-name ${{ inputs.os_name }} --os-version ${{ inputs.os_version }} --type=ipsw

    - name: Import symbols from OTA
      env:
          SENTRY_DSN: ${{ inputs.sentry_dsn }}
      shell: bash
      if: ${{ inputs.fetch_ota }}
      run: sentry-cli monitors run ${{ inputs.cron_monitor_slug }} -- python3 import_system_symbols_from_ipsw.py --os-name ${{ inputs.os_name }} --os-version ${{ inputs.os_version }} --type=ota
