name: import-system-symbols-from-ipsw
inputs:
  gcp_service_key:
    required: true
  os_name:
    required: true
  os_version:
    default: 'latest'
  fetch_ipsw:
    default: true
  fetch_ota:
    default: false

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-import-system-symbols
      with:
        gcp_service_key: ${{ inputs.gcp_service_key }}
    - name: Import symbols from IPSW
      shell: bash
      if: ${{ inputs.fetch_ipsw }}
      run: sentry-cli monitors run 09666664-597e-490c-ae2e-e1c22795fccd -- python3 import_system_symbols_from_ipsw.py --os-name ${{ inputs.os_name }} --os-version ${{ inputs.os_version }} --type=ipsw
    - name: Import symbols from OTA
      shell: bash
      if: ${{ inputs.fetch_ota }}
      run: sentry-cli monitors run 09666664-597e-490c-ae2e-e1c22795fccd -- python3 import_system_symbols_from_ipsw.py --os-name ${{ inputs.os_name }} --os-version ${{ inputs.os_version }} --type=ota
