name: Scheduled IPSW Import

on:
  schedule:
    - cron:  '0 */4 * * *' # Check for new IPSWs every 4 hours

  ## Remove before merging 
  push:
    branches:
      - chore/cron-monitoring

concurrency:
  group: import-system-symbols-from-ipsw-on-schedule
  cancel-in-progress: true

jobs:
  import-tvos-system-symbols-from-ipsw:
    runs-on: 'macos-12'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for tvOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.GCP_SERVICE_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: tvos
        os_version: latest
        fetch_ota: false
  import-ios-system-symbols-from-ipsw:
    runs-on: 'macos-12'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for iOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.GCP_SERVICE_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: ios
        os_version: latest
        fetch_ota: false
  import-macos-system-symbols-from-ipsw:
    runs-on: 'macos-12'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for macOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.GCP_SERVICE_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: macos
        os_version: latest
        fetch_ota: false
  import-watchos-system-symbols-from-ipsw:
    runs-on: 'macos-12'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for watchOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.GCP_SERVICE_KEY }}
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: watchos
        os_version: latest
        fetch_ota: false
