name: Import system symbols from IPSW

on: workflow_dispatch

concurrency:
  group: import-system-symbols-from-ipsw
  cancel-in-progress: true

jobs:
  import-tvos-system-symbols-from-ipsw:
    runs-on: 'macos-11'
    steps:
    - name: Import system symbols for tvOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.IOS_SYMBOL_IPSW_SERVICE_KEY }}
        os_name: tvos
        os_version: latest
  import-ios-system-symbols-from-ipsw:
    runs-on: 'macos-11'
    steps:
    - name: Import system symbols for iOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.IOS_SYMBOL_IPSW_SERVICE_KEY }}
        os_name: ios
        os_version: latest
  import-macos-system-symbols-from-ipsw:
    runs-on: 'macos-11'
    steps:
    - name: Import system symbols for macOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        gcp_service_key: ${{ secrets.IOS_SYMBOL_IPSW_SERVICE_KEY }}
        os_name: macos
        os_version: latest
  import-watchos-system-symbols-from-ipsw:
    runs-on: 'macos-11'
    steps:
    - name: Import system symbols for watchOS
      uses: ./.github/actions/import-system-symbols-ipsw
      with:
        gcp_service_key: ${{ secrets.IOS_SYMBOL_IPSW_SERVICE_KEY }}
        os_name: watchos
        os_version: latest
