name: Scheduled IPSW Import

on:
  schedule:
    - cron:  '0 */4 * * *' # Check for new IPSWs every 4 hours

  push:
      branches:
        - main
  
  pull_request:

concurrency:
  group: import-system-symbols-from-ipsw-on-schedule
  cancel-in-progress: true

jobs:
  import-tvos-system-symbols-from-ipsw:
    runs-on: 'macos-14'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for tvOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: tvos
        os_version: latest
        fetch_ota: false
        cron_monitor_slug: import-symbols-from-ipsw-tvos

  import-ios-system-symbols-from-ipsw:
    runs-on: 'macos-14'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for iOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: ios
        os_version: latest
        fetch_ota: false
        cron_monitor_slug: import-symbols-from-ipsw-ios

  import-macos-system-symbols-from-ipsw:
    runs-on: 'macos-14'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for macOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: macos
        os_version: latest
        fetch_ota: false
        cron_monitor_slug: import-symbols-from-ipsw-macos

  import-watchos-system-symbols-from-ipsw:
    runs-on: 'macos-14'
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for watchOS
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        sentry_dsn: ${{ secrets.SENTRY_DSN }}
        os_name: watchos
        os_version: latest
        fetch_ota: false
        cron_monitor_slug: import-symbols-from-ipsw-for-watchos
