name: Manual IPSW Import

on:
  workflow_dispatch:
    inputs:
      os_name:
        description: 'OS name to upload system symbols for'
        required: true
        type: choice
        options:
          - ios
          - macos
          - tvos
          - watchos
      os_version:
        description: 'OS version to upload system symbols for'
        required: true
        type: string
        default: 'latest'
      fetch_ipsw:
        description: 'Fetch IPSW?'
        required: false
        type: boolean
        default: true
      fetch_ota:
        description: 'Fetch OTA?'
        required: false
        type: boolean
        default: false

jobs:
  import-system-symbols-from-ipsw:
    runs-on: 'macos-14'
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Import system symbols for ${{ github.event.inputs.os_name }}
      uses: ./.github/actions/import-system-symbols-from-ipsw
      with:
        sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}s
        os_name: ${{ github.event.inputs.os_name }}
        os_version: ${{ github.event.inputs.os_version }}
        fetch_ipsw: ${{ github.event.inputs.fetch_ipsw == true }}
        fetch_ota: ${{ github.event.inputs.fetch_ota == true }}
        # XXX: this is just to make things work for manual 
        cron_monitor_slug: import-symbols-from-ipsw-${{ github.event.inputs.os_name }}